---
title: "mcfc01b"
author: "Phillip Abbott"
date: "March 9, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# MCFC01b

```{r}

library(tidyverse)

source("./mcfc01.R")
source("./mcfc03.R")


```




```{r}
Risk$Business_Unit__c %>% table() %>% pie(main="Business_Unit__c")
Risk$grc__Risk_Name__c %>% unique() %>% length()
Risk$Risk__Type__c %>% table() %>% pie(main="Risk__Type__c")
Risk$ExtractDate %>% table() %>% pie(main="ExtractDate")
Risk$ReportingMonth %>% table() %>% pie(main="ReportingMonth")
Risk$grc__Status__c %>% table() %>% pie(main="grc__Status__c")
Risk$Design_Element__c %>% unique() %>% length()
Risk$XactHE__Contractual_Allocation__c %>% table() %>% pie(main="XactHE__Contractual_Allocation__c")
Risk$Risk__Mitigation__c %>% table() %>% pie(main="Risk__Mitigation__c")
Risk$Row.Labels%>% unique() %>% length()
Risk$worst %>% abs() %>% log() %>% hist(main="log abs worst", breaks=99)
Risk$expected  %>% abs() %>% log( )%>% hist(main="log abs expected", breaks=99)
Risk$best %>% abs() %>% log() %>% hist(main="log abs best", breaks=99)
Risk$prob  %>% abs() %>% log()%>% hist(main="log abs prob", breaks=99)


```

## Extract Date <--> Reporting Month

this shows that there is a 1-1 correspondence between extract date and reporting month


```{r}


table(Risk$ExtractDate, Risk$ReportingMonth)



```



```{r}

# the_business_unit, the_extract_date, the_risk_type ) {




# filter by
# * Business_Unit__c
# * ExtractDate
# * Risk__Mitigation__c
# then clean up the data and analyze
mc $ some_good_data <- function(the_table, the_business_unit, the_extract_date, the_risk_mitigation ) {
  
  R2 <- the_table
  
  if ("All" != the_business_unit)  R2 <- R2[ the_table$Business_Unit__c==the_business_unit,]
  R2 <- R2[ the_table$ExtractDate==the_extract_date,]
  R2 <- R2[ the_table$Risk__Mitigation__c==the_risk_mitigation,]
  
  
  R2 <- R2 [!is.na(R2$prob),]
  R2 <- R2 [!is.na(R2$best),]
  R2 <- R2 [!is.na(R2$expected),]
  R2 <- R2 [!is.na(R2$worst),]
  R2 <- R2 [(R2$best < R2$expected) & (R2$expected < R2$worst), ]
  
  R2$prob <- R2$prob/100
  
  R2[, c("prob", "worst", "expected", "best")]
  
}




Risk <- read.csv("./risk_KA_11.csv", stringsAsFactors = FALSE)


# ignore null values  ==> 129824 rows
Risk <- Risk[Risk$Risk__Value__c!="NULL",] 
Risk <- Risk[Risk$Business_Unit__c!="#N/A",] # filter out the summation row
Risk <- Risk[!is.na(Risk$INDEX),]

#Risk <- Risk[Risk$Risk__Category__c=="Cost", ]
# Risk <- Risk[Risk$Risk__Value__c!="0.00",] 

Risk <- Risk %>% mutate(worst=as.numeric(as.character(Risk__Worst_Case__c)))
Risk <- Risk %>% mutate(expected=as.numeric(as.character(Risk__Value__c)))
Risk <- Risk %>% mutate(best=as.numeric(as.character(Risk__Best_Case__c)))
Risk$prob <- abs(Risk$prob)




bu0 <- Risk$Business_Unit__c %>% unique()
ed0 <- Risk$ExtractDate %>% unique()
rt0 <- Risk$Risk__Mitigation__c %>% unique()

llength <- (bu0%>%length()) * (ed0%>%length()) * (rt0%>%length())

bus_unit <- rep("NA", llength)
ext_date <- rep(0, llength)
risk_mit <- rep("NA", llength)
the_length <- rep(0, llength)

k <- 1

for ( bidx in bu0 %>% seq_along()) {
  for (eidx in ed0 %>% seq_along()) {
    for (ridx in rt0 %>% seq_along()) {
     
      # paste( bu0[bidx], ed0[eidx], rt0[ridx], ":", the_length, "\n") %>% cat()
      bus_unit[k] <- bu0[bidx]
      ext_date[k] <- ed0[eidx]
      risk_mit[k] <- rt0[ridx]
      the_length[k] <- Risk %>% mc$some_good_data( bu0[bidx], ed0[eidx], rt0[ridx]) %>% nrow() 
      k <- k + 1
    }
  }
}

filter_categories <- data.frame( bus_unit, ext_date, risk_mit, the_length)
View(filter_categories)

rm(Risk)

```




```{r}




mc $ make_histogram_discrete_filtered (Risk, "A14 Section 2", 43348, "Target", 999, 999)


```







GET https://dev.azure.com/{organization}/{project}/_apis/wit/classificationnodes/{structureGroup}/{path}?api-version=5.0



GET https://dev.azure.com/pma0734/MCFC02/_apis/wit/classificationnodes/Areas?api-version=5.0



```{r}

q0 <- Risk %>% mc $ get_the_filtered_data ( "A14 Section 2", 43348, "Target")

```



# on the object orientification of the R

```{r}

CShape <- function() {
  
  result <- new.env(emptyenv())
  result $ GetArea <- function() 0
  result
}

CSquare <- function(side) {
  
  parent_ <- CShape()
  result <- new.env(parent=parent_)
  result$side=side
  what_the_parent_has <- ls(parent_)
  for (k in seq_along(what_the_parent_has)) 
      assign(what_the_parent_has[k], parent_[[what_the_parent_has[k]]], envir=result)
  
  
  result $ GetArea <- function() side*side
  result
  
}


derive_from <- function( the_parent_class ) {
  parent_ <- the_parent_class()
  result <- new.env(parent=parent_)
  what_the_parent_has <- ls(parent_)
  
  ls(parent_) %>% map( function(it)  assign(it, parent_[[it]], envir=result) )
  
  result
}

CCircle <- function(radius) {
  
  result <- derive_from(CShape)
  
  result $ GetArea <- function () pi*radius
  
  result
  
}

a_square <- CSquare(1.5)
a_circle <- CCircle(1.5)

a_square $ GetArea()
a_circle $ GetArea()



```








